### ISSUE TITLE
Unusable - frezzes emacs

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-mode#2]
Copied from nyuhuhuu/wakatime-mode/11 where @yisraeldov says,

I installed this and when I enable the wakatime-mode it just freezes emacs when ever I try to edit a file. I'm assuming that it is getting stuck somewhere and not returning any error.

It's been stuck for about 10 min now, and I don't see any python processes running, so I'm assuming that it is an issue with the emacs code.

**Comment by nha** [comment]
I just installed waka time, and I am experiencing something similar, but not exactly the same.
I can type in my files just fine, except that it regularly freezes emacs for a few seconds.
Then the following error is displayed : 

error in process sentinel: An error occured while connecting to WakaTime (code 102). [X times]

have a very poor internet connection, so it may be related to that. I wouldn't say that it makes emacs unusable, but it is certainly annoying. Otherwise I could see myself use it, so thanks for building it :)

**Comment by alanhamlett** [comment]
This should be fixed now after a major refactor of the plugin code.
