### ISSUE TITLE
How does the wakatime-mode recognized the language?

### ISSUE THREAD

**Issue by Liutos** [wakatime/wakatime-mode#37]
I found there're about 55% of my languages is "Other", why the wakatime-mode can't recognized the language I used. Actually I spent a lot of time in writing some .org files, does wakatime-mode not treat the Org as a language? Thanks~

**Comment by sawthinkar** [comment]
I have the same issue here. Is there a way to get Other languages recognized?

**Comment by alanhamlett** [comment]
There's two ways to add support for languages:

1. A file extension rule server-side
2. Add/update the corresponding [Pygments Lexer](https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/lexers/) for the language

Do org-mode files always end with `.org`?

**Comment by sawthinkar** [comment]
In my case is .story files which are for Storyscript.

**Comment by Anton-Latukha** [comment]
@alanhamlett 

Yes, `Org-mode` files always use `.org` extensions.

**Comment by Anton-Latukha** [comment]
Solid explanation:

I've just tested this.

Yes, `Org-mode` files always use `.org`, since they can embody a lot of other languages - and so `file` utility classifies it differently based on the beginning of the file & contents. I've got `LaTeX`, `ASCII text` `Emacs Lisp` etc, so the distinction for the file is its extension.

Emacs itself recognizes `Org-mode` files based on the extension, I've just tested and observed that.

Also the Emacs "Major mode" can be a hint, when operating with `Org-mode` - Emacs uses `org-mode` major mode.

But other IDEs/editors also have support of `Org-mode` to some degree.

So the extension is the most efficient way overall.

Also studies usage of `.org` extention - seems like only `Org-mode` uses it:
https://fileinfo.com/extension/org - here ve observe that `.org` was used in the most ancient versions of Lotus Organizer https://en.wikipedia.org/wiki/IBM_Lotus_Organizer, year 1992.
https://filext.com/file-extension/ORG - some Hollywood FX by Pinnacle Systems

**Comment by Anton-Latukha** [comment]
Other IDEs/editors also have support of `Org-mode` to some degree.

So the extension is the most efficient way overall.

**Comment by Anton-Latukha** [comment]
Also studies the usage of `.org` extension.
Observed that we can conclude `.org` is sole for `Org-mode:

Source #1: https://filext.com/file-extension/ORG - some Hollywood FX by Pinnacle Systems video editing software extension.
Source #2: https://fileinfo.com/extension/org - here we observe that `.org` in IT was used in the most ancient versions of Lotus Organizer https://en.wikipedia.org/wiki/IBM_Lotus_Organizer, somewhere in the year 1992.

**Comment by SteamedFish** [comment]
I'm quite confused because, wakatime  cannot even recognize golang with Emacs. All golang becomes Other.
I tried vscode, found that wakatime can recognize golang with vscode.

There must be some difference between wakatime emacs extension and wakatime vscode extension, which I haven't figure out. 

> There's two ways to add support for languages:
> 
>     1. A file extension rule server-side
> 
>     2. Add/update the corresponding [Pygments Lexer](https://github.com/pygments/pygments/tree/master/pygments/lexers) for the language
> 
> 
> Do org-mode files always end with `.org`?

**Comment by notarock** [comment]
Bumping for interest - is there any way I can help make this plugin works with detecting the language for org-mode?

**Comment by thomasf** [comment]
the wakatime cli has a `--language` option, can that be used? Emacs could base the language on which mode is actually active instead of file extensions which is probably what you'd want.

**Comment by Anton-Latukha** [comment]
Above statement is not completely true.
The core design of Emacs is that Emacs has only one major-mode at one time. That is why there is distinction between major-mode and additionally loaded minor-modes. There may be only one major-mode at a time. Other modes should be loaded as minor-modes. Mixing several major-modes are not officially supported, and considered hacking the Emacs system. There is a packages that hack the system by creating custom major-mode and importing several major-modes into it, but that is considered direct hacking and refuted by Emacs maintainers.

So there is only one major-mode at a time. If people hack-in two - they are the ones that should care to make it work.

So, the name of the current major-mode Emacs operates in is stored in `major-mode` variable.

---

So, it is enough to binding the list of the major modes to the languages and tasks.

And even simplier and automatic:

The modes are direcrly named after the languages.

```
org-mode
markdown-mode
elisp-mode
haskell-mode
```

So just dropping the `-mode` and passing that string into `wakatime` should be enough.

**Comment by thomasf** [comment]
> The core design of Emacs is that Emacs has only one major-mode at one time.

Well you do have all the stuff that supports multiple major modes for one buffer.  Some of them uses multiple backing buffers with one major mode per buffer and indirect buffers to piece a buffer together and I am not completely sure that `major-mode` variable will always be correct in those cases. I could be wrong though.

https://www.emacswiki.org/emacs/MultipleModes



> So just dropping the -mode and passing that string into wakatime should be enough to support most cases by one action.

I think it's better to use an explicit list or leave the unknown modes to wakatime to figure out itself.

**Comment by thomasf** [comment]
> Mixing several major-modes are not officially supported, and considered hacking the Emacs system.

What does this even mean? Emacs is supposed to be flexible and the hackability factor is a part of the ethos of the whole project

**Comment by Anton-Latukha** [comment]
Well. @thomasf.

Person is asked to suggest a good solution.

And we are trying to find a good solution here. And I shown the most simple, effective, and legitimate official way to support all languages and particular modes of operation for the `wakatime`, because Emacs with the `major-mode` literally indicates the purpose of the active tab the person works in.

Answering:
> > Mixing several major-modes are not officially supported, and considered hacking the Emacs system.
> 
> What does this even mean? Emacs is supposed to be flexible and the hackability factor is a part of the ethos of the whole project

That Emacs Lisp is Turing complete does not mean that everything is allowed and that Emacs does not have any design and a mix-mash of chaos.

With this type of argument we can say that everything is impossible, since VSCode written in Turing complete language, so we should expect it being the chaos and ther is no solution.

Programs have a particular design. They are written in a particular structured way, and impose design and interfaces on the extentions. Emacs does the same.

---

When one glances over, ignores and actively passes by is so much red flags shown to him on the runway, there is no need to tell a person that he is responsible for the desigion to mix-mash major-modes into one, when it is clearly put that Emacs does not support it, and modes at all do not expect to be meshed togather, no one knows what gets overshadowed when you mix random modes togather.

---

StackOverflow "Emacs: Could one buffer have more than one major mode?": https://stackoverflow.com/questions/31736638/emacs-could-one-buffer-have-more-than-one-major-mode

> No, but...

---

Official Emacs mailing list: https://lists.gnu.org/archive/html/emacs-devel/2016-04/msg00677.html

> The changes that will be needed for supporting multiple modes in the same buffer will be extensive, whether you want it or not, so trying too hard to make it easier on modes to adapt will skew the design.

---

Wikipedia, article "Emacs": https://en.wikipedia.org/wiki/GNU_Emacs#Minor_modes

> A GNU Emacs editing buffer can use only one major mode at a time, but multiple minor modes can operate simultaneously.
> There is also a minor mode that allows multiple major modes to be used in a single file, for convenience when editing a document in which multiple programming languages are embedded.

---

Emacs Wiki:

* article "MultipleModes" you mention has a comment banner put by the Emacs Wiki administrator about the whole article, : https://www.emacswiki.org/emacs/MultipleModes

>  What a shame that there are multiple multiple mode modes. As soon as you need mode X that requires multiple mode M1, while already using another mode which uses multiple mode M2, you’re loading far more than you need to. Just because TIMTOWTDI (sorry for the perl-ism) doesn’t mean you must do it more than one way.

* article named "MajorMode" starts as: https://www.emacswiki.org/emacs/MajorMode
> Each buffer in Emacs is in a (single) major mode.

---

GNU.org, Emacs, article "Major-Modes": https://www.gnu.org/software/emacs/manual/html_node/emacs/Major-Modes.html

> Every buffer possesses a major mode, which determines the editing behavior of Emacs while that buffer is current. Since every buffer has exactly one major mode, there is no way to “turn off” a major mode; instead, you must switch to a different one.

**Comment by Anton-Latukha** [comment]
I write the: https://github.com/Anton-Latukha/Fundamental-Haskell

And I may say, when I write that, I write in the Org mode markup.
Not in LaTeX, not in Haskell. That are the snippets of code inside the Org-mode. But the major work and modus operandi is the Org mode. You open and use Org-mode, because you want to put that stuff inside the Org-mode.

I am happy for `wakatime` to just show me how much time I've spent writing notes and the book, What is inside the Babel blocks - is a petty detail that should be looked over for simplicity. Otherwise, you just try to overcomplicate things for people that provide the Open Source project to you for free and try to help you to th e opoint so they abandone bothering and implementing the feature.

**Comment by Anton-Latukha** [comment]
1. Emacs has one major-mode at a time.
2. Name of it is storred in the `major-mode` variable.
3. Valus of the variable is `<...>-mode` where `<...>` being in the major swath of cases literally the name of the language, and in other cases, `wakatime` can be literal and show the Emacs user the direct `<...>` name of the mode, aka `org-agenda`, it is even better doing it this way, since person recieves the true data he understands, and the `org` is note taking, and `org-agenda` is sheduling and time management, it is also true for other Emacs mode cases, just show them the `major-mode` name - and they would hag you and be marveled.

**Comment by thomasf** [comment]
there is js-mode js2-mode js3-mode. There definitely has to be a fallback to a list that is a defcustom and support some kind of matching between mode names and source types because they will not always match directly by strripping a -mode suffix from the major-mode name.

**Comment by thomasf** [comment]
> Also by sheer coincidence, I work right under the main Emacs maintainer, if it is still not clear that Emacs has one major-mode for a tab ("buffer" in Emacs terms), I can go on a limb and ask official response just for us one more time, but it would be a pity to bother a guy for that.

I have written tens of thousands of lines of emacs lisp so I know the language and environment very well thank you., stop trying to make this into some weird pissing contest. 

> Otherwise, you just try to overcomplicate things for people that provide the Open Source project to you for free, meanwhile listening to your complaints while trying to help you.

Well, for me wakatime cli is actually already handling this perfectly fine by its own so that simple solution is to add no new code to handle this. It seems like some people some how have a broken wakatime cli install, maybe old pygments (?).

**Comment by Anton-Latukha** [comment]
>     * s-mode, js2-mode and js3-mode exists and are all major modes

`--language LANGUAGE` accepts only valid values, and `js{,2,3}` - are not valid values.

**Comment by Anton-Latukha** [comment]
Responding: https://github.com/wakatime/wakatime-mode/issues/37#issuecomment-702195992
> I just wrote from a practical perspective..
> 
> Those multi major modes exists and they are in use so regardless how official the support is we should not create code in this package that might break or do the wrong thing if those packages are in use.

Sorry, multiple major modes are not supported by the Emacs community. Do not try to block the development of Emacs just because you broke the rules of the design of Emacs.

> There is no reason to break compatibility just because one's own idealised opinion how how something should work when it actually isn't guaranteed to work like that in the real world.

That is not mine opinion, it is an opinion of the GNU Emacs project. While your opinion is that you expect that hacks would be supported.

Compatibily can not be broken, because there is no protocol of compatibility established by you. While you broke the protocol of Emacs compatibility.

**Comment by Anton-Latukha** [comment]
And over that - the names of unsupported multiple major-modes that you have, would not be recognized by `wakatime`, since you are the one that named them, so you should not be worried, the code submitted would work for you just as before.

**Comment by thomasf** [comment]
You could easily have implemented better handling instead of arguing with me about not doing it... I'm blocking you now so I won't have to get any further notifications.

**Comment by Anton-Latukha** [comment]
There was no talk about development. You right of the gate simply blocked the PR without reading and understanding how it works, without any review, there were no suggestions on how to improve the code.

What was send out is a demand to not accept it and complain that code is not good enough because it is not not existent ephemeral ideal code you imagine.

I've could extend the code, but so much already works great for everybody, there is no need to make defcustoms and extending it, since it is already resilient.

To proactively support more languages then we currently get detected - there should be a list of compatibility between Emacs major-mode names and `wakatime`, so Emacs right away sends and `wakatime` accepts the language setting and so we rely less on heuristic autodetection which does not detect some stuff, this report exists because autodetection does not detects some stuff. So now we would use the both ways of detection simultaneously, and BTW to just send the `major-mode` info is way fewer computations.

**Comment by thomasf** [comment]
> There was no talk about development. You right of the gate simply blocked the PR without reading and understanding how it works, without any review, there were no suggestions on how to improve the code.

quoute from one of my earlier comments in this thread:

_"There definitely has to be a fallback to a list that is a defcustom and support some kind of matching between mode names and source types with the option to defer to wakatimecli/pygments because they will not always match directly by stripping a -mode suffix from the major-mode name. The defcustom can come with a set of defaults that are maintained inside this package as a default."_

maybe something along the lines of

```elisp
(defun wakatime-guess-file-type-from-major-mode ()
  (downcase (string-trim-right (symbol-name major-mode) "-mode")))


(defcustom wakatime-language-finder
  '((js2-mode "javascript")
    (js3-mode "javascript")
    (t wakatime-guess-file-type-from-major-mode))
  "...")
```

> 
> What was send out is a demand to not accept it and complain that code is not good enough because it is not a not existent ephemeral ideal code you imagine.
> 

I made a recommendation which most people would see as less strong than a demand. It's also a recommendation that is up to the maintainer/repository owner to do decide on, I just give my opinion.

**Comment by thomasf** [comment]
> The core design of Emacs is that Emacs has only one major-mode at one time.

Yes and  those multiple major modes modes effectively changes the major mode depending on where in the buffer the cursor is, this might or might not be what a user of wakatime-mode wants so it should be possible to opt in or out of that behavior.

**Comment by Anton-Latukha** [comment]
Please, understand how the recievement and prioritization of information works in `wakatime`.

And stop blocking work.

**Comment by thomasf** [comment]
Thats good then.

I still prefer a simple customization to opt out of this feature. For me wakatime-cli's own detection works fine and I don't want to override it.

And again , I am not blocking. I am not a maintainer and I can only make suggestions and recommendations. I have no power to block anything.

**Comment by Anton-Latukha** [comment]
If I understood your example - you show that what you wanted from modes - to respect the code block language - indeed would work with my `major-mode` process.

If you write a `elisp` code in the block - it would count it as ELisp code wtiring - wich is great

You actually provided a point in favour of using this `major-mode` process.

**Comment by thomasf** [comment]
> If you write a `elisp` code in the block - it would count it as ELisp code wtiring - wich is great

I would fork wakatime-mode if it started doing this. I don't want the same file to report as different language types.

**Comment by Anton-Latukha** [comment]
I am happy, it is great that is works for you and markdown, but official Org-mode Emacs documentation does not work for `wakatime` at all currently.

I submitted patches to `wakatime` so it does work. And this code in `wakatime-mode` would allow to support `org` and many other languages.

After code is merged - you always can improve it by sending patches.

Of cource you are also allowed to fork the project.

**Comment by Anton-Latukha** [comment]
`wakatime` has an option for languages, called `--language`.

When you write Markdown - the language is Markdown, when you open a `elisp` block and write Emacs Lisp code - it is Emacs Lisp language. Emacs reports the language into `wakatime --language` option.

If you want `--language` to be activity option - sorry - it is not - it is obviously for programming language reporting.

There is:
```
  --category CATEGORY   Category of this heartbeat activity. Can be "coding",
                        "building", "indexing", "debugging", "running tests",
                        "writing tests", "manual testing", "code reviewing",
                        "browsing", or "designing". Defaults to "coding".
```

If you want "writing notes/documentation" to be tracked - you need to upstream that option into `wakatime` upstream.

**Comment by thomasf** [comment]
What is Org-mode Emacs documentation?

Is it org mode files without an .org extension?

I just added an .org file to a project and it got identified correctly at once

![image](https://user-images.githubusercontent.com/330847/96011876-cc699000-0e43-11eb-9164-ca3ee19e05e6.png)

Also my notes repository which is almost all org mode files shows org mode as the language everywhere..

**Comment by thomasf** [comment]
I don't belive so but I could be wrong.. wakatime --version says 13.0.7 which is the version that was releases in february so I'm not sure your changes are released yet.

**Comment by Anton-Latukha** [comment]
May be.

It still not arrived into my system, and I not looked completely into automatic resolving of languages, in my case, in years of use - `wakatime` does not recognize the `org`, and I tracked the reason down to this behaviour.

The heading post and down the line: https://github.com/wakatime/wakatime-mode/issues/37#issue-383351185

**Comment by alanhamlett** [comment]
It's 2022! There's been some changes around language detection:

* We're using [chroma](https://github.com/wakatime/chroma) in the new Go [wakatime-cli](https://github.com/wakatime/wakatime-cli) to detect language client-side. We no longer use Pygments.
* Your [Custom Rules](https://wakatime.com/settings/rules) are now more powerful. They can match ends of files using `ends with` instead of `contains`. Good for overwriting the default language by file extension.
* However, if you're language isn't detected just [create an issue](https://github.com/wakatime/chroma/issues/new) and we will add support for the language for everyone without needing Custom Rules.
* IDE plugins (like wakatime-mode and vim-wakatime) shouldn't send `--language` to wakatime-cli. Instead they use [--alternate-language](https://github.com/wakatime/vim-wakatime/blob/441f5c7ce8adce1d30403bca26ea5e6a3a2b82e4/plugin/wakatime.vim#L503) because that tells wakatime-cli to first try detecting the language, then use the one from the IDE if wakatime-cli can't auto-detect a language. Either way, language detection should work without `--alternate-language`.

For now, I'll close this. If the new wakatime-cli isn't detecting `.org` files then [create an issue](https://github.com/wakatime/chroma/issues/new) and we'll add support for that and any language.
